server:
  port: 11000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka

spring:
  main:
    web-application-type: reactive
  application:
    name: mileage-gateway
  cloud:
    gateway:
      routes:
        - id: boardDevStudyService
          uri: lb://BTAKA-BOARD-DEV-STUDY-SERVICE
          predicates:
            - Path=/board/dev/**
          filters:
            - RewritePath=/board/dev/?(?<path>.*), /api/v1//board/dev/$\{path}
        - id: authService
          uri: lb://BTAKA-AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<path>.*), /api/v1/auth/$\{path}
        - id: userService
          uri: lb://BTAKA-AUTH-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/?(?<path>.*), /api/v1/user/$\{path}
        - id: configService
          uri: lb://BTAKA-CONFIG-SERVICE
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/?(?<path>.*), /api/v1/config/$\{path}