server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
  level:
    root: info
    log4j2: info
    guide.triple: info

spring:
  main:
    web-application-type: reactive
  application:
    name: mileage-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalLoggingFilter
          args:
            baseMessage: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: mileageCommandService
          uri: lb://MILEAGE-COMMAND-SERVICE
          predicates:
            - Path=/events
        - id: mileageUserInfoService
          uri: lb://MILEAGE-QUERY-SERVICE
          predicates:
            - Path=/get/**
        - id: mileageHistoryService
          uri: lb://MILEAGE-QUERY-SERVICE
          predicates:
            - Path=/history/**