version: '3'

services:
  triple.mileage.ms.svr:
    image: roseoutz/triple-mileage-ms-svr:1.0.0
    container_name: mileage.ms.svr
    restart: always
    depends_on:
      - mysql
    ports:
      - "9201:9201"
  mysql:
    image: mysql:8.0.29
    container_name: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: db/env/db.env
    environment:
      - TZ="Asia/Seoul"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test123

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "user_sync:1:1,history_sync:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
