server:
  port: 9301
  servlet:
    application-display-name: Mileage Query Server

spring:
  application:
    name: MILEAGE-QUERY-SERVICE
  profiles:
    active: test

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka/
  instance:
    hostname: mileageQueryService
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
  level:
    root: info
    log4j2: info
    guide.triple: info

springdoc:
  api-docs:
    enabled: true
    path: /api/docs
  swagger-ui:
    path: swagger.html

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      host: 127.0.0.1
      username: test
      password: test123
      database: triple_mileage
      authentication-database: admin
      repositories:
        type: reactive