server:
  port: 9201
  servlet:
    application-display-name: Mileage Query Server

spring:
  application:
    name: MILEAGE_QUERY_SERVER
  profiles:
    active: test

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:12000/eureka/
  instance:
    hostname: authService
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /v3/api-docs/swagger.html

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      host: 127.0.0.1
      username: test
      password: test123
      database: triple_mileage
      authentication-database: admin
      repositories:
        type: reactive