server:
  port: 9401
  servlet:
    application-display-name: Mileage Data Proxy Server

spring:
  application:
    name: MILEAGE_DATA_PROXY_SERVER
  profiles:
    active: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: mileage-user
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      host: 127.0.0.1
      username: test
      password: test123
      database: triple_mileage
      authentication-database: admin
      repositories:
        type: reactive

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
  level:
    root: info
    guide.triple: info
    org.springframework.data.r2dbc: info

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:h2:mem:mileage;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/triple?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: test123
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      max-idle-time: 30m

---
spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/triple?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: test123
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      max-idle-time: 30m

---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: r2dbc:mysql://mysql:3306/triple?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: test123
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      max-idle-time: 30m