server:
  port: 9201 #java -jar spring-5.jar --server.port=8083
  servlet:
    application-display-name: Mileage Service
    #    context-path: /sso
    session:
      timeout: 7200
      cookie:
        name: JSESSIONID


spring:
  application:
    name: MILEAGE
  profiles:
    active: test
#  messages:
#    basename: messages/message, messages/message-error, messages/message-test
#    encoding: UTF-8


logging:
  charset:
    console: UTF-8
  level:
    root: info
    log4jdbc.log4j2: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    poolSize: 1
    property:
      prefix: ENC(
      suffix: )

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    hikari:
      jdbc-url: jdbc:log4jdbc:h2:mem:mileage;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: sa
      password:
      pool-name: hikari-db-pool
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    platform: mysql
    hikari:
      poolName: hikari-default-
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://192.168.11.8:3306/bandi?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: ENC(459cd884243381acaf6e7e94d650de35)
      password: ENC(03d5879466de10561a9182eba53cd88c)
      maximumPoolSize: 50
      connectionTimeout: 10000
      validationTimeout: 5000
      autoCommit: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy
        jdbc:
          batch_size: 20
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 500
        show-sql: true
        format_sql: true